---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-llma-bot
  namespace: student-llma-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: student-llma-bot
  template:
    metadata:
      labels:
        app: student-llma-bot
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: student-llma-bot
        image: 'ghcr.io/equillibrium/studentllmabot:latest'
        envFrom:
        - secretRef:
            name: student-llma-bot
