---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT}
  namespace: ${PROJECT}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${PROJECT}
  template:
    metadata:
      labels:
        app: ${PROJECT}
      annotations:
        kubernetes.io/change-cause: "${COMMIT_MESSAGE}"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: ${PROJECT}
        image: ${IMAGE}:latest
        envFrom:
        - secretRef:
            name: ${PROJECT}
      - name: redis
        image: redis
