---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${PROJECT}"
  namespace: "${PROJECT}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "${PROJECT}"
  template:
    metadata:
      labels:
        app: "${PROJECT}"
      annotations:
        kubernetes.io/change-cause: "${COMMIT_MESSAGE}"
    spec:
      serviceAccountName: "${PROJECT}"
      containers:
      - name: "${PROJECT}"
        image: ${IMAGE}:latest
        volumeMounts:
          - name: bot-data
            mountPath: /var/lib/telegram-bot-api
        envFrom:
        - secretRef:
            name: "${PROJECT}"
      - name: redis
        image: redis:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis-data
      - name: local-api-server
        image: aiogram/telegram-bot-api:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: "${PROJECT}"
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: bot-data
            mountPath: /var/lib/telegram-bot-api
      volumes:
        - name: redis-data
          hostPath:
            path: /data/redis
            type: DirectoryOrCreate
        - name: bot-data
          emptyDir: {}
