---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT}
  namespace: ${PROJECT}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${PROJECT}
  template:
    metadata:
      labels:
        app: ${PROJECT}
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: student-llma-bot
        image: ${IMAGE}:latest
        envFrom:
        - secretRef:
            name: ${PROJECT}
