---
name: Build docker image
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build bot docker image
    runs-on: k3s-runner
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: 'true'
          cache-from: 'ghcr.io/equillibrium/studentllmabot:latest'
          cache-to: 'ghcr.io/equillibrium/studentllmabot:latest'
          tags: 'ghcr.io/equillibrium/studentllmabot:latest'

  k3s:
    name: Deploy to k3s
    runs-on: k3s-runner
    needs: build

    steps:
      - name: Kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods