---
name: Build docker image
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build bot docker image

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx build --tag ghcr.io/studentllmabot/bot:latest --file Dockerfile . --push
